CSHARP/oenik_prog3_2019_2_e66y8m/AnimeTranslatingDatabase.Web/Models/AnimeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AnimeTranslatingDatabase.Web.Models
{
    public class AnimeViewModel
    {
        public AnimeW EditedAnime { get; set; }
        public List<AnimeW> ListOfAnimes { get; set; }
    }
}

CSHARP/oenik_prog3_2019_2_e66y8m/AnimeTranslatingDatabase.Web/Controllers/AnimeController.cs
using System;
using System.Collections.Generic;
using AnimeTranslatingDatabase.AnimeLogic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using AnimeTranslatingDatabase.Web.Models;
using AnimeTranslatingDatabase.Repository;
using System.ComponentModel.DataAnnotations;
using AnimeTranslatingDatabase.Data;

namespace AnimeTranslatingDatabase.Web.Controllers
{
    public class AnimeController : Controller
    {
        ILogic logic;
        IMapper mapper;
        AnimeViewModel avm;
        public AnimeController()
        {
            logic = new Logic();
            mapper = MapperFactory.CreateMapper();

            avm = new AnimeViewModel();
            avm.EditedAnime = new AnimeW();
            var animes = logic.GetAllAnime();
            avm.ListOfAnimes = mapper.Map<IList<Data.Anime>, List<Models.AnimeW>>(animes);
        }

        private AnimeW GetAnimeModel(int id)
        {
            Anime anime = logic.GetAllAnime().Where(x => x.Anime_ID == id).FirstOrDefault();
            return mapper.Map<Data.Anime, Models.AnimeW>(anime);
        }

        // GET: Anime
        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("AnimeIndex", avm);
        }

        // GET: Anime/Details/5
        public ActionResult Details(int id)
        {
            return View("AnimeDetails", GetAnimeModel(id));
        }

        // POST: Anime/Remove/5
        public ActionResult Remove(int id)
        {
            TempData["editResult"] = "Something went wrong with the delete";
            if (logic.DeleteAnime(id))
            {
                TempData["editResult"] = "Delete was succesful";
            }
            return RedirectToAction("Index");
        }

        // POST: Anime/Edit/5
        public ActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            avm.EditedAnime = GetAnimeModel(id);
            return View("AnimeIndex", avm);

        }

        // POST /Anime/Edit + Anime + editAction
        [HttpPost]
        public ActionResult Edit(AnimeW anime, string editAction)
        {
            if (ModelState.IsValid && anime != null)
            {
                TempData["editResult"] = "Succesful editing";
                if (editAction == "AddNew")
                {
                    logic.InsertAnime($"{anime.Name}_{anime.Release}_{anime.EpisodeCount}_{anime.Type}_{anime.Score}_{anime.Translator_ID}");
                }
                else
                {
                    if (!logic.EditAnime(anime.ID, $"{anime.Name}_{anime.Release}_{anime.EpisodeCount}_{anime.Type}_{anime.Score}_{anime.Translator_ID}"))
                    {
                        TempData["editResult"] = "Failed editing";
                    }
                }
                return RedirectToAction("Index");
            }
            else
            {
                ViewData["editAction"] = "Edit";
                avm.EditedAnime = anime;
                return View("AnimeIndex", avm);
            }           
        }       
    }
}

CSHARP/oenik_prog3_2019_2_e66y8m/AnimeTranslatingDatabase.Web/Views/Anime/AnimeDetails.cshtml
@model AnimeTranslatingDatabase.Web.Models.AnimeW

@{
    ViewBag.Title = "AnimeDetails";
}

<h2> Datasheet of one anime </h2>

@Html.ActionLink("Back to the future", "Index");

<table>
    <tr>
        <td>@Html.DisplayNameFor(m => m.ID)</td>
        <td>@Html.DisplayFor(m => m.ID)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Name)</td>
        <td>@Html.DisplayFor(m => m.Name)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Release)</td>
        <td>@Html.DisplayFor(m => m.Release)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.EpisodeCount)</td>
        <td>@Html.DisplayFor(m => m.EpisodeCount)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Type)</td>
        <td>@Html.DisplayFor(m => m.Type)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Score)</td>
        <td>@Html.DisplayFor(m => m.Score)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Translator_ID)</td>
        <td>@Html.DisplayFor(m => m.Translator_ID)</td>
    </tr>
</table>

CSHARP/oenik_prog3_2019_2_e66y8m/AnimeTranslatingDatabase.Web/Views/Anime/AnimeEdit.cshtml
@model AnimeTranslatingDatabase.Web.Models.AnimeW

<h2>Edit one anime</h2>

@using (Html.BeginForm("Edit", "Anime"))
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.ID);
    @Html.Hidden("editAction", ViewData["editAction"].ToString());

    
    <div class="editor-label">@Html.LabelFor(m => m.Name)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Name)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Release)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Release)</div>

    <div class="editor-label">@Html.LabelFor(m => m.EpisodeCount)</div>
    <div class="editor-field">@Html.EditorFor(m => m.EpisodeCount)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Type)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Type)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Score)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Score)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Translator_ID)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Translator_ID)</div>

    <input type="submit" value="SEND" />
}

CSHARP/oenik_prog3_2019_2_e66y8m/AnimeTranslatingDatabase.Web/Views/Anime/AnimeIndex.cshtml
@model AnimeTranslatingDatabase.Web.Models.AnimeViewModel
@{
    ViewBag.Title = "AnimeIndex";
}

<h2>Anime Index</h2>

<p style="color:red; font-weight:bold">@TempData["editResult"]</p>

@Html.Partial("AnimeEdit", Model.EditedAnime)

@Html.Partial("AnimeList", Model.ListOfAnimes)

CSHARP/oenik_prog3_2019_2_e66y8m/AnimeTranslatingDatabase.Web/Views/Anime/AnimeList.cshtml
@model IEnumerable<AnimeTranslatingDatabase.Web.Models.AnimeW>

@{ 
    ViewBag.Title = "AnimeList";
}

<h2>List of animes</h2>

@if (Model.Count() == 0)
{
    <p>No anime added yet</p>    
}
else
{
<table border="1" style="text-align:center">
    <tr>
        <th>@Html.DisplayNameFor(m => m.First().ID)</th>
        <th>@Html.DisplayNameFor(m => m.First().Name)</th>
        <th>@Html.DisplayNameFor(m => m.First().Release)</th>
        <th>@Html.DisplayNameFor(m => m.First().EpisodeCount)</th>
        <th>@Html.DisplayNameFor(m => m.First().Type)</th>
        <th>@Html.DisplayNameFor(m => m.First().Score)</th>
        <th>@Html.DisplayNameFor(m => m.First().Translator_ID)</th>
        <th>Datasheet</th>
        <th>Delete</th>
        <th>Edit</th>


    </tr>
    @foreach (var item in Model)
    {
<tr>
    <td>@Html.DisplayFor(m => item.ID)</td>
    <td style="text-align:left">@Html.DisplayFor(m => item.Name)</td>
    <td>@Html.DisplayFor(m => item.Release).ToString().TrimEnd('0', ':')</td>
    <td>@Html.DisplayFor(m => item.EpisodeCount)</td>
    <td>@Html.DisplayFor(m => item.Type)</td>
    <td>@Html.DisplayFor(m => item.Score)</td>
    <td>@Html.DisplayFor(m => item.Translator_ID)</td>
    <td>@Html.ActionLink("[SHOW]", "Details", new { id = item.ID })</td>
    <td>@Html.ActionLink("[DEL]", "Remove", new { id = item.ID })</td>
    <td>@Html.ActionLink("[EDIT]", "Edit", new { id = item.ID })</td>
</tr>
    }
</table>
}